---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors

  goimports:
    local-prefixes: github.com/monotek/mongodb_exporter

linters:
  disable-all: true
  enable:
    - depguard
    - goimports
    - ineffassign
    - govet
    - staticcheck

issues:
  exclude-use-default: false
